### ISSUE TITLE
Bugs 

### ISSUE THREAD

**Issue by Stevie94** [Juanes165/ProjectSanke#17]
- the game can be paused after it has been over.

- if u keep a direction key pressed n then change to another one,  it'll take too long. 

- Change the game level while its paused freeze the game.

**Comment by Juanes165** [comment]
the first is not a bug at all, it can wait. The second is caused for the system designed by daniel to avoid the automorision bug, i guess normal people shouldn´t keep the direction key pressed. The third one is the truly worrying bug

**Comment by srd4** [comment]
Already solved the first problem with a double condition inside pauseMs function. For the second "problem", solutions seem to be worst than the dissease so we'll have to stick with playing like normal functioning human beings do (not holding keys). The third is not a bug, when you click outside the canvas you have to click inside again for key events to be recognized, the game is not freezed. And you are not even supposted to be able to change diffculty after the game started anyways.
