### ISSUE TITLE
About general project development.

### ISSUE THREAD

**Issue by srd4** [Juanes165/ProjectSanke#2]
With Esteban, a few moments ago, we were messing around with the code and trying to understand, clean and apply some solutions to several different problems we currently have with it. Some of them seem to be organizational like technical debt (we are moving on to new problems without implementing good solutions to the ones before), algorithm application, compatibility between algorithms, documentation consistency and others.

The thing here is, we have NO time. And the best way of optimizing work on this is to think about the basic stuff the game needs to be completely functional (in a pragmatic sense of the word) since this is what would be graded be teachers in the first place. Later we can focus in styling and others.

So, for now what we currently have **solved** on this git is:
Systems for:
- Automatic movement.
- Collisions (itself, canvas).
- Change of direction.
- Food generation.
- Growth.
- Pause.

Now, inside what we have solved, we found the following **problems**:
- Dumb suicide bug.
- Food respawning under snake.
- OnTic event checks implementation (generalize them).
- Clean drawgame().
- Docstring and function naming consistency.

And things left that aren't even yet implemented:
- Score and highest score record.
- Reset buttons.
- Increase speed (difficulty).
- Styling.

**Comment by Juanes165** [comment]
I suggest to rename the Dumb suicide bug to "automorision"
