### ISSUE TITLE
Cheat when game is paused.

### ISSUE THREAD

**Issue by srd4** [Juanes165/ProjectSanke#3]
One can cheat the game if presses pause and then the arrows. If you are playing to win you can use the instantaneous pause as an advantage.

I was thinking about making a delay (like a countdown before un-pausing) so pausing becomes so slow that is unuseful to use it for cheating

**Comment by Juanes165** [comment]
We can edit the KeyPressed function in order to block the keys when the game is paused, just allowing to press the P letter

**Comment by Juanes165** [comment]
I think we wont solve that
